// build-sw.mjs — writes dist/sw.js with a precache list of what vite ACTUALLY
// emitted. Runs after `vite build` (see package.json "build").
//
// WHY GENERATED, not hand-written: vite hashes asset names, so any list typed
// by hand is correct exactly until the next build. LESSONS.md records a
// service worker that served a 503 error page over a cached app; the class of
// bug is "the worker's idea of the app disagreed with the app". Reading the
// real output directory removes the opportunity.
//
// WHY NOT WORKBOX: spec §1's dependency budget is suncalc only. This is the
// whole of what workbox would do here, and it is auditable in one screen.

import { readdirSync, statSync, writeFileSync, readFileSync, existsSync } from 'node:fs';
import { join, relative, sep } from 'node:path';

const DIST = 'dist';
const VERSION = /export const VERSION = '([^']+)'/.exec(
  readFileSync('src/version.js', 'utf8'),
)?.[1];

if (!VERSION) {
  console.error('build-sw: could not read VERSION from src/version.js');
  process.exit(1);
}
if (!existsSync(DIST)) {
  console.error(`build-sw: ${DIST}/ does not exist — run vite build first`);
  process.exit(1);
}

/** Every emitted file, as a root-absolute URL path. */
function walk(dir) {
  const out = [];
  for (const name of readdirSync(dir)) {
    const full = join(dir, name);
    if (statSync(full).isDirectory()) out.push(...walk(full));
    else out.push(`/${relative(DIST, full).split(sep).join('/')}`);
  }
  return out;
}

const all = walk(DIST);

// Precache the ENTIRE app shell and all logic (spec §10). The only exclusions
// are files that are not part of the running app: the worker itself (it is the
// thing doing the caching) and Cloudflare's `_headers`, which is a deploy
// directive and never fetched by the page.
const EXCLUDE = new Set(['/sw.js', '/_headers']);
const precache = all.filter((p) => !EXCLUDE.has(p)).sort();

if (!precache.some((p) => p === '/index.html')) {
  console.error('build-sw: index.html is missing from the build output');
  process.exit(1);
}
if (!precache.some((p) => p.endsWith('.js') && p.startsWith('/assets/'))) {
  console.error('build-sw: no JS bundle found in the build output');
  process.exit(1);
}

const CACHE = `photo-field-tools-v${VERSION}`;

const sw = `// GENERATED by build-sw.mjs — do not edit. Rebuild instead.
//
// Cache name carries the app version (Doctrine §7b), so a stale cache is
// diagnosable rather than mysterious: the build stamp on screen and this name
// move together, in the same commit.
const CACHE = ${JSON.stringify(CACHE)};
const PRECACHE = ${JSON.stringify(precache, null, 2)};

self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    // addAll is atomic: if ANY entry fails the whole install fails and the old
    // worker stays in charge. That is what stops a half-populated cache from
    // serving a broken app — the failure mode this file exists to prevent.
    await cache.addAll(PRECACHE);
    await self.skipWaiting();
  })());
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    const names = await caches.keys();
    await Promise.all(names.filter((n) => n !== CACHE).map((n) => caches.delete(n)));
    await self.clients.claim();
  })());
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;

  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;   // nothing else is ours to serve

  event.respondWith((async () => {
    const cache = await caches.open(CACHE);

    // CACHE FIRST, and deliberately so: spec §10 says there are NO runtime
    // network fetches. Every byte the app needs is in PRECACHE, so a cache hit
    // is the correct and complete answer, online or off.
    const hit = await cache.match(url.pathname);
    if (hit) return hit;

    // A navigation to any in-app address resolves to the shell — the router is
    // hash-based, so this only matters for a stray path, and it must never
    // fall through to a network error page.
    if (req.mode === 'navigate') {
      const shell = await cache.match('/index.html');
      if (shell) return shell;
    }

    try {
      return await fetch(req);
    } catch (err) {
      // NEVER serve an error page over the cached app (LESSONS.md 7d). If we
      // have the shell, the shell is a better answer than a browser error.
      const shell = await cache.match('/index.html');
      if (shell) return shell;
      return new Response('Offline and not cached.', {
        status: 504,
        headers: { 'Content-Type': 'text/plain' },
      });
    }
  })());
});
`;

writeFileSync(join(DIST, 'sw.js'), sw);
console.log(`build-sw: wrote dist/sw.js — cache "${CACHE}", ${precache.length} precached files`);
for (const p of precache) console.log(`  · ${p}`);
