import { defineConfig } from 'vite';

// Vanilla ES modules, no framework, no plugins. suncalc is the only runtime
// dependency and vite bundles it into the app — spec §10 forbids CDN loading.
//
// The service worker is NOT generated by a plugin. `build-sw.mjs` runs after
// the build and writes a precache list from the files vite actually emitted.
// A hand-written list would drift the first time a chunk name changed, and a
// workbox dependency would break the dependency budget in spec §1 for a job
// that is thirty lines.
export default defineConfig({
  build: {
    outDir: 'dist',
    // No sourcemaps in the shipped build: they would be precached too, roughly
    // doubling what an offline install has to store for no field benefit.
    sourcemap: false,
    target: 'es2020',
    rollupOptions: {
      output: {
        // Stable, hashed names so the precache list is exact and a changed
        // file can never be served from a stale entry.
        entryFileNames: 'assets/[name]-[hash].js',
        chunkFileNames: 'assets/[name]-[hash].js',
        assetFileNames: 'assets/[name]-[hash][extname]',
      },
    },
  },
  server: { port: 5173 },
  preview: { port: 4173 },
});
